logging:
  file: logs/server.log
  config: classpath:logback-spring.xml
  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %-5level [%thread]: %message%n%ex{4}"

server:
  port: ${OPENDB_PORT:6463}
  connection-timeout: 300000
  tomcat:
    max-http-post-size: 4096
    max-threads: 5

opendb:
  mgmt:
    user: ${OPENDB_LOGIN:openplacereviews:test_1}
    privateKey: ${OPENDB_PK:base64:PKCS#8:MD4CAQAwEAYHKoZIzj0CAQYFK4EEAAoEJzAlAgEBBCAOpUDyGrTPRPDQRCIRXysxC6gCgSTiNQ5nVEjhvsFITA==}
    publicKey: ${OPENDB_PBK:base64:X.509:MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAETxKWXg3jhSxBtYhTxO/zMj6S0jO95ETUehlZ7yR150gFSmxqJcLE4YQDZ6t/Hn13kmaZbhSFMNsAX+kbeUMqbQ==}
  files-backup:
    overpass-cache: ${OVERPASS_CACHE_DIR:overpass_cache}
#    directory: ${FILE_BLOCKS_DIR:blocks}
  serverUrl: ${SERVER_URL:http://localhost:6463/}
  authUrl: ${AUTH_URL:api/test-auth.html}
  email:
    sendgrid-api: ${SENDGRID_API:}
  auth-opr-prefix: ${AUTH_OPR_PREFIX:oprw-}
  patch-version: ${OPENDB_PATCHVERSION:}

oauth:
  osm:
    apiKey: ${OSM_OAUTH_KEY:}
    secret: ${OSM_OAUTH_SECRET:}
  github:
    apiKey: ${GITHUB_OAUTH_KEY:}
    secret: ${GITHUB_OAUTH_SECRET:}
  google:
    apiKey: ${GOOGLE_OAUTH_KEY:}
    secret: ${GOOGLE_OAUTH_SECRET:}    

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE:15MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE:15MB}
      enabled: true
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: update
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/openplacereviews}
    username: ${DB_USER:test}
    password: ${DB_PWD:test}
    hikari:
      maximumPoolSize: 4
  userdatasource:
    url: ${USER_DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${USER_DB_USER:test}
    password: ${USER_DB_PWD:test}
    hikari:
      maximumPoolSize: 4      
# classpath:/static/

---
spring.jpa.hibernate.ddl-auto: validate
spring:
  profiles: productions

logging:
  config: classpath:logback-spring.xml

server:
  tomcat.max-threads: 50
  address: ${SERVER_ADDRESS:127.0.0.1} #keep it behind proxy
  tomcat:
    protocol_header: x-forwarded-proto
    remote_ip_header: x-forwarded-for
    accesslog:
      enabled: true
      rotate: false
      pattern: '%h %l %u %t "%r" %s %b %D "%{Referer}i" "%{User-Agent}i"'

